In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.text_cell_render.rendered_html{font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))


# 1 tensorflow v2.xx에서 v1사용하기

In [4]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() # tensorflow V2 비활성화하고 v1활성화
import numpy as np
import pandas as pd

Instructions for updating:
non-resource variables are not supported in the long term


## Tensorflow
- 데이터 흐름 그래프(tensor 객체의 흐름)을 사용하는 수치 계산 라이브러리
- 그래프는 node(연산)와 edge로 구성
- sess =tf.Session()을 이용해서 실행환경
- sess.run()을 통해서 실행결과를 확인

In [5]:
# 1단계 : tensor(상수 노드 하나) 정의
node1 = tf.constant('Hello, Tensorflow')
# 2단계 : 세션(연산을 실행하는 환경) 생성
sess = tf.Session()
# 3단계 : 실제 실행 및 출력
print(sess.run(node1))
print(sess.run(node1).decode())

b'Hello, Tensorflow'
Hello, Tensorflow


In [13]:
# 간단한 연산 tensor 그래프
# 1. 그래프 정의
node1 = tf.constant(10, dtype=tf.float16)
node2 = tf.constant(20, dtype=tf.float16)
node3 = tf.add(node1, node2)
# 2. 세션 생성
sess = tf.Session()
# 3.실행결괴
print(sess.run([node1,node2,node3]))

[10.0, 20.0, 30.0]


In [11]:
# 타입변경
import numpy as np
node1= tf.constant(np.array([1,2,3]), dtype=tf.int16)
node2= tf.cast(node1, dtype=tf.float32)
sess= tf.Session()
print(sess.run([node1, node2]))

[array([1, 2, 3], dtype=int16), array([1., 2., 3.], dtype=float32)]


In [16]:
# 평균값 계산: tf.reduce_mean()
data= np.array([1.,2.,3.,4.])
m= tf.reduce_mean(data)
sess= tf.Session()
print(sess.run(m))

2.5


In [19]:
# tf.random_normal([size]): 평균이 0이고 표준편차가 1인 난수 size개 발생
w= tf.random_normal([3])
sess= tf.Session()
sess.run(w)

array([ 0.8130884, -1.3318462, -0.8962071], dtype=float32)

In [21]:
# 변수 코드
w= tf.Variable(tf.random_normal([1]))
sess= tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(w)

array([1.6440265], dtype=float32)

# 2. tensorflow v1을 이용한 회귀분석 구현
## 2.1 독립변수가 x가 1개, 타겟(종속)변수 y가 1개

In [27]:
# tensor 그래프 정의
# 데이터 셋 확보
x = np.array([1,2,3])
y = np.array([2,3,4])
# weight와 bias
W = tf.Variable(tf.random.normal([1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')
# Hat, Hypothesis : 결과는 numpy 배열
H = W * x + b
# cost function (손실함수 : mse )
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 W, b를 찾는 것
cost 함수는 2차함수이므로 곡선 그래프. 곡선위 미분값이 0이 되는 방향
(경사하강법GradientDescent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# 세션 생성
sess = tf.Session()
# W, b 초기화
sess.run(tf.global_variables_initializer())
# 6000번 학습 (v2 에서의 fit함수)
for step in range(6001):
    _, cost_val, W_val, b_val = sess.run([train, cost, W, b])
    if step%300==0:
        print("{}번째 cost:{}, W:{}, b:{}".format(step, cost_val, W_val, b_val))

0번째 cost:18.45536231994629, W:[-0.39202058], b:[0.1374729]
300번째 cost:0.0014944514259696007, W:[1.0447911], b:[0.8981793]
600번째 cost:0.00035263379686512053, W:[1.0217577], b:[0.9505398]
900번째 cost:8.32049991004169e-05, W:[1.0105689], b:[0.9759747]
1200번째 cost:1.9633238480309956e-05, W:[1.0051339], b:[0.98832947]
1500번째 cost:4.6330619625223335e-06, W:[1.002494], b:[0.9943306]
1800번째 cost:1.0935696082015056e-06, W:[1.0012116], b:[0.9972456]
2100번째 cost:2.5864810027087515e-07, W:[1.0005895], b:[0.9986607]
2400번째 cost:6.133294760957142e-08, W:[1.000287], b:[0.99934775]
2700번째 cost:1.463443766169803e-08, W:[1.0001402], b:[0.9996813]
3000번째 cost:3.4973612894617645e-09, W:[1.0000685], b:[0.9998444]
3300번째 cost:8.466400913675898e-10, W:[1.0000335], b:[0.9999233]
3600번째 cost:2.0462091743223e-10, W:[1.0000167], b:[0.99996233]
3900번째 cost:5.770909791702472e-11, W:[1.0000091], b:[0.9999802]
4200번째 cost:5.328478283606053e-11, W:[1.0000087], b:[0.9999811]
4500번째 cost:5.328478283606053e-11, W:[1.0000

In [29]:
4

In [30]:
W_, b_

(array([1.0000087], dtype=float32), array([0.9999811], dtype=float32))

In [31]:
def predict(x):
    return W_[0] * x + b_[0]

In [32]:

predict(5)

6.000024616718292


## 2.2 predict을 위한 placeholder 이용
- placeholder : 외부에서 데이터를 입력받을 수 있는 노드

In [33]:
x = tf.placeholder(dtype=tf.float32)
H = 1*x + 1
sess = tf.Session()
sess.run([x, H], feed_dict={x : np.array([40,50])})

[array([40., 50.], dtype=float32), array([41., 51.], dtype=float32)]

In [36]:
# tensor 그래프 정의
# 데이터 셋 확보
x_data = np.array([1,2,3])
y_data = np.array([2,3,4])
# placeholder 설정(x, y)
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight와 bias
W = tf.Variable(tf.random.normal([1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')
# Hat, Hypothesis : 결과는 numpy 배열
H = W * x + b
# cost function (손실함수 : mse )
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 W, b를 찾는 것
cost 함수는 2차함수이므로 곡선 그래프. 곡선위 미분값이 0이 되는 방향
(경사하강법GradientDescent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# 세션 생성
sess = tf.Session()
# W, b 초기화
sess.run(tf.global_variables_initializer())
# 6000번 학습 (v2 에서의 fit함수)
for step in range(6001):
    _, cost_val, W_val, b_val = sess.run([train, cost, W, b],
                                        feed_dict={x:x_data,
                                                   y:y_data})
    if step%300==0:
        print("{}번째 cost:{}, W:{}, b:{}".format(step, cost_val, W_val, b_val))


0번째 cost:38.10966873168945, W:[-1.5273888], b:[0.96662605]
300번째 cost:0.02776999957859516, W:[0.8069194], b:[1.4389178]
600번째 cost:0.006552610080689192, W:[0.9062098], b:[1.2132071]
900번째 cost:0.0015461430884897709, W:[0.9544408], b:[1.1035666]
1200번째 cost:0.0003648214042186737, W:[0.9778695], b:[1.0503079]
1500번째 cost:8.608311327407137e-05, W:[0.98925006], b:[1.0244372]
1800번째 cost:2.0310913896537386e-05, W:[0.9947782], b:[1.0118703]
2100번째 cost:4.792717390955659e-06, W:[0.9974634], b:[1.0057662]
2400번째 cost:1.1310897889416083e-06, W:[0.99876773], b:[1.0028012]
2700번째 cost:2.6709878397923603e-07, W:[0.9994011], b:[1.0013613]
3000번째 cost:6.32083256846272e-08, W:[0.99970865], b:[1.0006622]
3300번째 cost:1.5026918376292997e-08, W:[0.99985784], b:[1.000323]
3600번째 cost:3.6894600707881864e-09, W:[0.9999297], b:[1.0001602]
3900번째 cost:8.638873505439904e-10, W:[0.99996597], b:[1.0000772]
4200번째 cost:2.390455333678432e-10, W:[0.9999823], b:[1.0000405]
4500번째 cost:8.710306781400945e-11, W:[0.999

In [37]:

# 예측하기
sess.run(H, feed_dict={x:5})

array([5.9999704], dtype=float32)

## 2.3 scale이 다른 데이터들의 회귀분석 구현(scale 조정X)

In [39]:
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
# placeholder 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight & bias
W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))
# Hypothesis
H = W * x + b
# cost (손실함수)
cost = tf.reduce_mean(tf.square(H-y))
# 경사하강법
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.0001)
train = optimizer.minimize(cost)
# Session & 변수 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습
for step in range(1, 6001):
    _, cost_val = sess.run([train, cost], feed_dict={x:x_data, y:y_data})
    if step%300==0:
        print("{}/6000번째 cost:{}".format(step+1, cost_val))

301/6000번째 cost:111.75020599365234
601/6000번째 cost:80.32357025146484
901/6000번째 cost:80.02237701416016
1201/6000번째 cost:79.98916625976562
1501/6000번째 cost:79.95935821533203
1801/6000번째 cost:79.93057250976562
2101/6000번째 cost:79.90281677246094
2401/6000번째 cost:79.87602233886719
2701/6000번째 cost:79.8501968383789
3001/6000번째 cost:79.82527160644531
3301/6000번째 cost:79.80117797851562
3601/6000번째 cost:79.77796936035156
3901/6000번째 cost:79.7555923461914
4201/6000번째 cost:79.73395538330078
4501/6000번째 cost:79.71308898925781
4801/6000번째 cost:79.69295501708984
5101/6000번째 cost:79.67354583740234
5401/6000번째 cost:79.65482330322266
5701/6000번째 cost:79.63673400878906
6001/6000번째 cost:79.61929321289062


# 2.4 scale이 다른 데이터들의 회귀분석 구현(scale 조정O)
- scale 조정방법 : 모든 데이터를 일정범위내로 조정
- normalization(정규화) : 모든 데이터를 0~1 사이로 조정- 
X - Xmin normalization = ───────────── Xmax - Xmin * 위의 식보다 라이브러리 추천(sklearn.preprocessing.MinMaxScaler)
standarization(표준화) : 데이터의 평균을 0, 표준편차를 1로 조정 X - Xmean standarization = ───────────────── Xstd(표준편차) * 위의 식보다 라이브러리 추천(sklearn.preprocessing.StandardScaler)

In [40]:
# 라이브러리 쓰지 않고 정규화
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
# x_data.min(), x_data.max(), x_data.mean(), x_data.std()
norm_scaled_x_data = (x_data - x_data.min()) / (x_data.max() - x_data.min())
norm_scaled_y_data = (y_data - y_data.min()) / (y_data.max() - y_data.min())

In [41]:
# 라이브러리를 사용하여 정규화
x_data = np.array([1, 2, 5, 8, 10]).reshape(-1,1)
y_data = np.array([5, 15, 68, 80, 95]).reshape(-1,1)
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler() # 독립변수 x를 정규화시킬 객체
scaler_x.fit(x_data)
norm_scaled_x_data = scaler_x.transform(x_data)
scaler_y = MinMaxScaler() # 종속(타겟)변수 y를 정규화시킬 객체
norm_scaled_y_data = scaler_y.fit_transform(y_data)
norm_scaled_y_data

array([[0.        ],
       [0.11111111],
       [0.7       ],
       [0.83333333],
       [1.        ]])

In [ ]:

# 라이브러리 쓰지 않고 표준화
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
stan_scaled_x_data = (x_data - x_data.mean()) / x_data.std()
stan_scaled_y_data = (y_data - y_data.mean()) / y_data.std()
np.column_stack([x_data, norm_scaled_x_data, stan_scaled_x_data])

In [ ]:

np.column_stack([y_data, norm_scaled_y_data, stan_scaled_y_data])

In [43]:
# 라이브러리를 사용하여 표준화
x_data = np.array([1, 2, 5, 8, 10]).reshape(-1,1)
y_data = np.array([5, 15, 68, 80, 95]).reshape(-1,1)

from sklearn.preprocessing import StandardScaler
scaler_x= StandardScaler()
stan_scaled_x_data= scaler_x.fit_transform(x_data)
scaler_y= StandardScaler()
stan_scaled_y_data= scaler_y.fit_transform(y_data)


In [46]:
# 스케일 조정된 데이터를 다시 복구 : inverse_transform() 이용
scaler_y.inverse_transform(stan_scaled_y_data)

array([[ 5.],
       [15.],
       [68.],
       [80.],
       [95.]])

In [48]:
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
# placeholder 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight & bias
W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))
# Hypothesis
H = W * x + b
# cost (손실함수)
cost = tf.reduce_mean(tf.square(H-y))
# 경사하강법
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# Session & 변수 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습
for step in range(1, 6001):
    _, cost_val = sess.run([train, cost], feed_dict={x:norm_scaled_x_data, 
                                                     y:norm_scaled_y_data})
    if step%300==0:
        print("{}/6000번째 cost:{}".format(step, cost_val))

300/6000번째 cost:0.010682969354093075
600/6000번째 cost:0.009995486587285995
900/6000번째 cost:0.009825870394706726
1200/6000번째 cost:0.009784016758203506
1500/6000번째 cost:0.009773687459528446
1800/6000번째 cost:0.009771140292286873
2100/6000번째 cost:0.009770509786903858
2400/6000번째 cost:0.009770351462066174
2700/6000번째 cost:0.009770316071808338
3000/6000번째 cost:0.009770306758582592
3300/6000번째 cost:0.009770301170647144
3600/6000번째 cost:0.009770301170647144
3900/6000번째 cost:0.009770302101969719
4200/6000번째 cost:0.009770302101969719
4500/6000번째 cost:0.009770302101969719
4800/6000번째 cost:0.009770302101969719
5100/6000번째 cost:0.009770302101969719
5400/6000번째 cost:0.009770302101969719
5700/6000번째 cost:0.009770302101969719
6000/6000번째 cost:0.009770302101969719
